// BANCO DE DADOS COMPLETO
const produtos = [
  {id: 1, cat: "Cervejas", nome: "Brahma Latão 473ml", preco: 5.50, pack: {nome: "Caixa c/ 12", preco: 66.00}, destaque: true},
  {id: 2, cat: "Cervejas", nome: "Antarctica Latão 473ml", preco: 5.50, pack: {nome: "Caixa c/ 12", preco: 66.00}},
  {id: 3, cat: "Cervejas", nome: "Corona Latão 473ml", preco: 7.50, pack: {nome: "Caixa c/ 12", preco: 90.00}, destaque: true},
  {id: 4, cat: "Cervejas", nome: "Budweiser Latão 473ml", preco: 6.50, pack: {nome: "Caixa c/ 12", preco: 78.00}},
  {id: 5, cat: "Cervejas", nome: "Spaten Latão 473ml", preco: 6.50, pack: {nome: "Caixa c/ 12", preco: 78.00}, destaque: true},
  {id: 6, cat: "Cervejas", nome: "Original Latão 473ml", preco: 6.50, pack: {nome: "Caixa c/ 12", preco: 78.00}},
  {id: 7, cat: "Cervejas", nome: "Stella Artois Latão 473ml", preco: 7.50, pack: {nome: "Caixa c/ 12", preco: 90.00}},
  {id: 8, cat: "Cervejas", nome: "Heineken Latão 473ml", preco: 7.00, pack: {nome: "Caixa c/ 12", preco: 84.00}, destaque: true},
  {id: 9, cat: "Cervejas", nome: "Amstel Latão 473ml", preco: 5.50, pack: {nome: "Caixa c/ 12", preco: 66.00}},
  {id: 10, cat: "Cervejas", nome: "Império Latão 473ml", preco: 5.00, pack: {nome: "Caixa c/ 12", preco: 60.00}},
  {id: 11, cat: "Cervejas", nome: "Itaipava Latão 473ml", preco: 4.50, pack: {nome: "Caixa c/ 12", preco: 54.00}},
  {id: 12, cat: "Cervejas", nome: "Lokal Latão 473ml", preco: 4.00, pack: {nome: "Caixa c/ 12", preco: 48.00}},
  {id: 13, cat: "Cervejas", nome: "Corona Long Neck 330ml", preco: 8.50, pack: {nome: "Pack c/ 6", preco: 51.00}, destaque: true},
  {id: 14, cat: "Cervejas", nome: "Budweiser Long Neck 330ml", preco: 7.50, pack: {nome: "Pack c/ 6", preco: 45.00}},
  {id: 15, cat: "Cervejas", nome: "Spaten Long Neck 330ml", preco: 7.50, pack: {nome: "Pack c/ 6", preco: 45.00}},
  {id: 16, cat: "Cervejas", nome: "Stella Pure Gold 330ml", preco: 8.00, pack: {nome: "Pack c/ 6", preco: 48.00}},
  {id: 17, cat: "Cervejas", nome: "Stella Puro Malte 330ml", preco: 8.00, pack: {nome: "Pack c/ 6", preco: 48.00}},
  {id: 18, cat: "Cervejas", nome: "Heineken Long Neck 330ml", preco: 8.00, pack: {nome: "Pack c/ 6", preco: 48.00}, destaque: true},
  {id: 19, cat: "Cervejas", nome: "Império Lager Long Neck 330ml", preco: 6.50},
  {id: 20, cat: "Cervejas", nome: "Império Gold Long Neck 330ml", preco: 6.00},
  {id: 21, cat: "Cervejas", nome: "Império Ultra Long Neck 330ml", preco: 7.00},
  {id: 22, cat: "Cervejas", nome: "Brahma Cracudinha 300ml", preco: 3.50},
  {id: 23, cat: "Cervejas", nome: "Antarctica Cracudinha 300ml", preco: 3.50},
  {id: 24, cat: "Cervejas", nome: "Original Cracudinha 300ml", preco: 3.50},
  {id: 25, cat: "Cervejas", nome: "Brahma Zero Álcool Lata", preco: 5.00},
  {id: 26, cat: "Cervejas", nome: "Heineken Zero Long Neck 330ml", preco: 8.00},
  {id: 27, cat: "Destilados", nome: "Vodka Absolut 750ml", preco: 85.00, destaque: true},
  {id: 28, cat: "Destilados", nome: "Vodka Smirnoff 900ml", preco: 40.00, destaque: true},
  {id: 29, cat: "Destilados", nome: "Vodka Kovak 1L", preco: 26.00},
  {id: 30, cat: "Destilados", nome: "Vodka Leonoff 900ml", preco: 20.00},
  {id: 31, cat: "Destilados", nome: "Gin Okay Dry 900ml", preco: 25.00},
  {id: 32, cat: "Destilados", nome: "Gin Leonoff Dry 900ml", preco: 30.00},
  {id: 33, cat: "Destilados", nome: "Gin Leonoff Purple Fresh 900ml", preco: 30.00},
  {id: 34, cat: "Destilados", nome: "Gin Leonoff Watermelon 900ml", preco: 30.00},
  {id: 35, cat: "Destilados", nome: "Gin Leonoff Pineberry 900ml", preco: 30.00},
  {id: 36, cat: "Destilados", nome: "Gin Rocks Tradicional 1L", preco: 35.00, destaque: true},
  {id: 37, cat: "Destilados", nome: "Gin Rocks Sicilians Lemon 1L", preco: 35.00},
  {id: 38, cat: "Destilados", nome: "Gin Rocks Strawberry 1L", preco: 35.00},
  {id: 39, cat: "Destilados", nome: "Gin Rocks Watermelon 1L", preco: 35.00},
  {id: 40, cat: "Destilados", nome: "Gin Rocks Sunset 1L", preco: 35.00},
  {id: 41, cat: "Destilados", nome: "Gin QN Tradicional 900ml", preco: 28.00},
  {id: 42, cat: "Destilados", nome: "Gin QN Melancia 900ml", preco: 28.00},
  {id: 43, cat: "Destilados", nome: "Gin QN Maçã Verde 900ml", preco: 28.00},
  {id: 44, cat: "Destilados", nome: "Gin QN Tropical 900ml", preco: 28.00},
  {id: 45, cat: "Destilados", nome: "Gin QN Strawberry 900ml", preco: 28.00},
  {id: 46, cat: "Destilados", nome: "Gin Tônica QN Frutas Vermelhas 355ml", preco: 9.00},
  {id: 47, cat: "Destilados", nome: "Gin Tônica QN Melancia 355ml", preco: 9.00},
  {id: 48, cat: "Destilados", nome: "Gin Tônica QN Maçã Verde 355ml", preco: 9.00},
  {id: 49, cat: "Destilados", nome: "Gin Tônica Amora 355ml", preco: 9.00},
  {id: 50, cat: "Destilados", nome: "Gin Tônica QN Pitaya 355ml", preco: 9.00},
  {id: 51, cat: "Destilados", nome: "Gin Tônica QN Tangerina 355ml", preco: 9.00},
  {id: 52, cat: "Destilados", nome: "Gin Tônica QN Pink Lemonade 355ml", preco: 9.00},
  {id: 53, cat: "Destilados", nome: "Skol Beats Senses Lata", preco: 7.00, destaque: true},
  {id: 54, cat: "Destilados", nome: "Skol Beats GT Lata", preco: 7.50},
  {id: 55, cat: "Destilados", nome: "Skol Beats Red Mix Lata", preco: 7.00},
  {id: 56, cat: "Destilados", nome: "Skol Beats Red Mix Long Neck", preco: 10.00},
  {id: 57, cat: "Destilados", nome: "Ice Cabaré Frutas Vermelhas", preco: 8.50},
  {id: 58, cat: "Destilados", nome: "Ice 51 Balada", preco: 7.00},
  {id: 59, cat: "Destilados", nome: "Ice 51 Limão", preco: 7.00},
  {id: 60, cat: "Destilados", nome: "Ice Kovak Limão", preco: 6.00},
  {id: 61, cat: "Destilados", nome: "Ice Smirnoff Lions Limão", preco: 8.00},
  {id: 62, cat: "Destilados", nome: "Ice Syn Limão Long Neck", preco: 6.00},
  {id: 63, cat: "Destilados", nome: "Ice Syn Limão Plástico", preco: 4.00},
  {id: 64, cat: "Destilados", nome: "Ice We Mix Morango e Kiwi", preco: 5.00},
  {id: 65, cat: "Destilados", nome: "Ice We Mix Pêssego c/ Chá Preto", preco: 5.00},
  {id: 66, cat: "Destilados", nome: "Ice We Mix Frutas Verdes c/ Chá Verde", preco: 5.00},
  {id: 67, cat: "Destilados", nome: "Ice We Mix Limão e Gengibre", preco: 5.00},
  {id: 68, cat: "Destilados", nome: "Ice We Mix Melancia e Hortelã", preco: 5.00},
  {id: 69, cat: "Destilados", nome: "Pink Moon Rosé 275ml", preco: 6.50},
  {id: 70, cat: "Destilados", nome: "Pink Moon Rosé 750ml", preco: 20.00},
  {id: 71, cat: "Destilados", nome: "Pink Moon Pêssego 275ml", preco: 6.50},
  {id: 72, cat: "Destilados", nome: "Pink Moon Uva 275ml", preco: 6.50},
  {id: 73, cat: "Destilados", nome: "Pink Moon Uva 600ml", preco: 10.00},
  {id: 74, cat: "Destilados", nome: "Stempel Uva 600ml", preco: 16.00},
  {id: 75, cat: "Destilados", nome: "Stempel Abacaxi 600ml", preco: 16.00},
  {id: 76, cat: "Destilados", nome: "Stempel Rosé 600ml", preco: 16.00},
  {id: 77, cat: "Destilados", nome: "Whisky Ballantines 1L", preco: 85.00},
  {id: 78, cat: "Destilados", nome: "Whisky Ballantines 750ml", preco: 75.00},
  {id: 79, cat: "Destilados", nome: "Whisky Cavalo Branco 1L", preco: 75.00, destaque: true},
  {id: 80, cat: "Destilados", nome: "Whisky Cavalo Branco 500ml", preco: 45.00},
  {id: 81, cat: "Destilados", nome: "Whisky Red Label 1L", preco: 95.00, destaque: true},
  {id: 82, cat: "Destilados", nome: "Whisky Red Label 750ml", preco: 85.00},
  {id: 83, cat: "Destilados", nome: "Whisky Jack Daniels Maçã Verde 1L", preco: 180.00},
  {id: 84, cat: "Destilados", nome: "Whisky Jack Daniels Tradicional 1L", preco: 160.00, destaque: true},
  {id: 85, cat: "Destilados", nome: "Whisky Jack Daniels Fire 1L", preco: 160.00},
  {id: 86, cat: "Destilados", nome: "Whisky Buchanan's 12 Anos 1L", preco: 220.00},
  {id: 87, cat: "Destilados", nome: "Whisky Buchanan's 12 Anos 750ml", preco: 180.00},
  {id: 88, cat: "Destilados", nome: "Whisky Old Parr 1L", preco: 160.00},
  {id: 89, cat: "Destilados", nome: "Whisky Woodford Reserve 750ml", preco: 180.00},
  {id: 90, cat: "Destilados", nome: "Licor 43 Edição Especial", preco: 220.00},
  {id: 91, cat: "Destilados", nome: "Licor Baileys 50ml", preco: 10.00},
  {id: 92, cat: "Destilados", nome: "Licor Bananinha Reggiane", preco: 22.00},
  {id: 93, cat: "Destilados", nome: "Licor Amarula 750ml", preco: 165.00},
  {id: 94, cat: "Destilados", nome: "Cachaça da Roça Menta", preco: 20.00},
  {id: 95, cat: "Destilados", nome: "Cachaça da Roça Paçoquita", preco: 20.00},
  {id: 96, cat: "Destilados", nome: "Cachaça Praianinha 970ml", preco: 16.00},
  {id: 97, cat: "Destilados", nome: "Pytu Amarelinha", preco: 25.00},
  {id: 98, cat: "Destilados", nome: "Pytu Limão", preco: 25.00},
  {id: 99, cat: "Destilados", nome: "Cachaça 51 1L", preco: 15.00},
  {id: 100, cat: "Destilados", nome: "Cachaça Velho Barreiro 1L", preco: 18.00},
  {id: 101, cat: "Destilados", nome: "Barrigudinha", preco: 7.00},
  {id: 102, cat: "Destilados", nome: "Caninha da Roça", preco: 6.00},
  {id: 103, cat: "Destilados", nome: "Vinho Pérgola Suave 1L", preco: 25.00},
  {id: 104, cat: "Destilados", nome: "Vinho Galiotto Suave 1L", preco: 25.00},
  {id: 105, cat: "Destilados", nome: "Vinho Casa Rodrigues Suave 1L", preco: 25.00},
  {id: 106, cat: "Destilados", nome: "Vinho Casa Rodrigues Seco 1L", preco: 25.00},
  {id: 107, cat: "Destilados", nome: "Vinho Colorado Suave 1L", preco: 30.00},
  {id: 108, cat: "Destilados", nome: "Vinho Colorado Seco 1L", preco: 30.00},
  {id: 109, cat: "Destilados", nome: "Combo QN Sunshine Whisky Trad.", preco: 16.50},
  {id: 110, cat: "Destilados", nome: "Combo QN Sunshine Whisky c/ Coco", preco: 16.50},
  {id: 111, cat: "Destilados", nome: "Combo QN Sunshine Vodka c/ Manga", preco: 16.50},
  {id: 112, cat: "Destilados", nome: "Combo QN Sunshine Gin c/ Melancia", preco: 16.50},
  {id: 113, cat: "Energéticos", nome: "QN Melancia 2L", preco: 10.00, pack: {nome: "Pack c/ 4", preco: 40.00}},
  {id: 114, cat: "Energéticos", nome: "QN Maçã Verde 2L", preco: 10.00, pack: {nome: "Pack c/ 4", preco: 40.00}},
  {id: 115, cat: "Energéticos", nome: "Red Hot 2L Tradicional", preco: 10.00},
  {id: 116, cat: "Energéticos", nome: "Minotauro 2L", preco: 10.00},
  {id: 117, cat: "Energéticos", nome: "Baly Tradicional 2L", preco: 13.00, destaque: true},
  {id: 118, cat: "Energéticos", nome: "Baly Maçã Verde 2L", preco: 13.00},
  {id: 119, cat: "Energéticos", nome: "Baly Melancia 2L", preco: 13.00},
  {id: 120, cat: "Energéticos", nome: "Baly Tadala 2L", preco: 13.00},
  {id: 121, cat: "Energéticos", nome: "Baly Tropical 2L", preco: 13.00},
  {id: 122, cat: "Energéticos", nome: "One 2L", preco: 7.00},
  {id: 123, cat: "Energéticos", nome: "Red Bull Tradicional", preco: 10.00, pack: {nome: "Pack c/ 4", preco: 40.00}, destaque: true},
  {id: 124, cat: "Energéticos", nome: "Red Bull Tropical", preco: 10.00},
  {id: 125, cat: "Energéticos", nome: "Monster Tradicional", preco: 12.00, destaque: true},
  {id: 126, cat: "Energéticos", nome: "Monster Manga", preco: 12.00},
  {id: 127, cat: "Refrigerantes", nome: "Sukita Uva 2L", preco: 8.00},
  {id: 128, cat: "Refrigerantes", nome: "Sukita Laranja 2L", preco: 8.00},
  {id: 129, cat: "Refrigerantes", nome: "Coca-Cola 2L", preco: 12.00, destaque: true},
  {id: 130, cat: "Refrigerantes", nome: "Coca-Cola Retornável 2L", preco: 8.00},
  {id: 131, cat: "Refrigerantes", nome: "Limoneto H2OH 1,5L", preco: 9.00},
  {id: 132, cat: "Refrigerantes", nome: "Mineirinho 2L", preco: 10.00},
  {id: 133, cat: "Refrigerantes", nome: "Guaraná Antarctica 2L", preco: 12.00, destaque: true},
  {id: 134, cat: "Refrigerantes", nome: "Grapete 2L", preco: 9.50},
  {id: 135, cat: "Refrigerantes", nome: "Flexa Cola 2L", preco: 7.00},
  {id: 136, cat: "Refrigerantes", nome: "Flexa Laranja 2L", preco: 7.00},
  {id: 137, cat: "Refrigerantes", nome: "Flexa Uva 2L", preco: 7.00},
  {id: 138, cat: "Refrigerantes", nome: "Flexa Guaraná 2L", preco: 7.00},
  {id: 139, cat: "Refrigerantes", nome: "Coca-Cola Lata 350ml", preco: 5.50},
  {id: 140, cat: "Refrigerantes", nome: "Guaraná Antarctica Lata 350ml", preco: 5.50},
  {id: 141, cat: "Refrigerantes", nome: "Gatorade Laranja 500ml", preco: 7.00},
  {id: 142, cat: "Refrigerantes", nome: "Gatorade Blueberry 500ml", preco: 7.00},
  {id: 143, cat: "Refrigerantes", nome: "Gatorade Uva 500ml", preco: 7.00},
  {id: 144, cat: "Refrigerantes", nome: "Gatorade Morango 500ml", preco: 7.00},
  {id: 145, cat: "Refrigerantes", nome: "Água Saborizada Maçã Verde", preco: 4.00},
  {id: 146, cat: "Refrigerantes", nome: "Água Saborizada Tangerina", preco: 4.00},
  {id: 147, cat: "Refrigerantes", nome: "Água Saborizada Limão", preco: 4.00},
  {id: 148, cat: "Refrigerantes", nome: "Água Mineral S/ Gás 510ml", preco: 3.00},
  {id: 149, cat: "Refrigerantes", nome: "Água Mineral C/ Gás 510ml", preco: 3.50},
  {id: 150, cat: "Refrigerantes", nome: "Água Mineral S/ Gás 1,5L", preco: 5.00},
  {id: 151, cat: "Refrigerantes", nome: "Água Mineral C/ Gás 1,5L", preco: 7.00},
  {id: 152, cat: "Refrigerantes", nome: "Pirakids", preco: 2.50},
  {id: 153, cat: "Refrigerantes", nome: "Toddynho", preco: 3.50},
  {id: 154, cat: "Refrigerantes", nome: "Limoneto H2OH 500ml", preco: 5.50},
  {id: 155, cat: "Refrigerantes", nome: "Guaravita 290ml", preco: 2.50},
  {id: 156, cat: "Refrigerantes", nome: "Guaraplus 290ml", preco: 2.50},
  {id: 157, cat: "Água", nome: "Galão Cascataí 20L", preco: 13.00},
  {id: 158, cat: "Água", nome: "Galão Serra 20L", preco: 10.00},
  {id: 159, cat: "Gelo/Carvão", nome: "Gelo Filtrado 5kg", preco: 15.00, destaque: true},
  {id: 160, cat: "Gelo/Carvão", nome: "Gelo Escama 20kg", preco: 30.00},
  {id: 161, cat: "Gelo/Carvão", nome: "Gelo de Coco Verde", preco: 4.00, destaque: true},
  {id: 162, cat: "Gelo/Carvão", nome: "Gelo de Coco Maçã Verde", preco: 4.00},
  {id: 163, cat: "Gelo/Carvão", nome: "Gelo de Coco Melancia", preco: 4.00},
  {id: 164, cat: "Gelo/Carvão", nome: "Gelo de Coco Maracujá", preco: 4.00},
  {id: 165, cat: "Gelo/Carvão", nome: "Gelo de Coco Morango", preco: 4.00},
  {id: 166, cat: "Gelo/Carvão", nome: "Carvão Frigogil 2kg", preco: 12.00, destaque: true},
  {id: 167, cat: "Gelo/Carvão", nome: "Carvão Oliveira 2kg", preco: 15.00},
  {id: 168, cat: "Gelo/Carvão", nome: "Carvão Araruama 2,4kg", preco: 17.00},
  {id: 169, cat: "Gelo/Carvão", nome: "Carvão Araruama 5,5kg", preco: 35.00},
  {id: 170, cat: "Churrasco", nome: "Sal Grosso", preco: 5.00},
  {id: 171, cat: "Churrasco", nome: "Sal Parrilla Argentino 1kg", preco: 12.00},
  {id: 172, cat: "Churrasco", nome: "Sal Parrilla Chimichurri 1kg", preco: 12.00},
  {id: 173, cat: "Churrasco", nome: "Sal Parrilla Lemon Pepper 250g", preco: 7.00},
  {id: 174, cat: "Churrasco", nome: "Sal Parrilla Argentino 250g", preco: 7.00},
  {id: 175, cat: "Churrasco", nome: "Sal Parrilla Chimichurri 250g", preco: 7.00},
  {id: 176, cat: "Churrasco", nome: "Sal Parrilla Defumado 250g", preco: 7.00},
  {id: 177, cat: "Churrasco", nome: "Pasta Pão de Alho Bacon 500g", preco: 15.00},
  {id: 178, cat: "Churrasco", nome: "Pasta Pão de Alho Queijo 500g", preco: 15.00},
  {id: 179, cat: "Churrasco", nome: "Pasta Pão de Alho Trad. 500g", preco: 15.00, destaque: true},
  {id: 180, cat: "Churrasco", nome: "Molho Churrasco e Grelhado", preco: 8.00},
  {id: 181, cat: "Churrasco", nome: "Molho Alho", preco: 8.00},
  {id: 182, cat: "Churrasco", nome: "Molho Pimenta Vulcão", preco: 8.00},
  {id: 183, cat: "Churrasco", nome: "Molho Pimenta Biquinho", preco: 8.00},
  {id: 184, cat: "Churrasco", nome: "Farofa Picanha", preco: 8.00},
  {id: 185, cat: "Churrasco", nome: "Farofa Tradicional", preco: 8.00},
  {id: 186, cat: "Churrasco", nome: "Farofa Costelinha", preco: 8.00},
  {id: 187, cat: "Churrasco", nome: "Tempero Completo Churrasco", preco: 8.00},
];